FROM node:21.6.1

ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV REACT_APP_GOOGLE_KEY=$REACT_APP_GOOGLE_KEY
ENV REACT_APP_GOOGLE_TRACKING_ID=$REACT_APP_GOOGLE_TRACKING_ID

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install -g serve
COPY . .
RUN serve -s build
EXPOSE 3000
CMD [ "npm", "run", "start" ]
