name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker image
      run: docker build -t amb0u/react-app:${{ github.run_number }} .

    - name: Push Docker image to Docker Hub
      run: docker push amb0u/react-app:${{ github.run_number }}

    - uses: actions/checkout@v2
      name: changing the deployment of git repo
      with:
        repository: 'amb0u/atlas-apps'
        token: ${{ secrets.GIT_PASSWORD }}
    - name: modify the image
      run: |
        git config --local user.email '$(echo "$EMAIL")'
        git config --local user.name '$(echo "$GIT_USERNAME")'
        pwd
        sed -i 's|image: amb0u/react-app:.*|image: amb0u/react-app:'$(echo "$GITHUB_RUN_NUMBER")'|' prod/web-deployment.yml
        ## cat dev/web-deployment.yml
        git add .
        git commit -m 'Update manifest version'
        git push origin master
      env:
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        RUN_NUMBER: ${{ github.run_number }}
        EMAIL: ${{ github.MAIL }}
