name: Docker Build and Push

on:
  push:
    branches:
      - master  # adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # adjust Node.js version as needed

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t amb0u/web-atlas:latest .
        docker push amb0/web-atlas:latest

