name: Docker Build and Push

on:
  push:
    branches:
      - master  # adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.6.1'  # adjust Node.js version as needed

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: amb0u/atlas-web
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
